export const countries = [
    { value: 'CA', label: 'Canada' },
    { value: 'US', label: 'United States' },
];

export const states = {
    'CA': [
        { value: 'AB', label: 'Alberta' },
        { value: 'BC', label: 'British Columbia' },
        { value: 'MB', label: 'Manitoba' },
        { value: 'NB', label: 'New Brunswick' },
        { value: 'NL', label: 'Newfoundland and Labrador' },
        { value: 'NS', label: 'Nova Scotia' },
        { value: 'ON', label: 'Ontario' },
        { value: 'PE', label: 'Prince Edward Island' },
        { value: 'QC', label: 'Quebec' },
        { value: 'SK', label: 'Saskatchewan' },
        { value: 'NT', label: 'Northwest Territories' },
        { value: 'NU', label: 'Nunavut' },
        { value: 'YT', label: 'Yukon' },
    ],
    'US': [
        { value: 'AL', label: 'Alabama' },
        { value: 'AK', label: 'Alaska' },
        { value: 'AZ', label: 'Arizona' },
        { value: 'AR', label: 'Arkansas' },
        { value: 'CA', label: 'California' },
        { value: 'CO', label: 'Colorado' },
        { value: 'CT', label: 'Connecticut' },
        { value: 'DE', label: 'Delaware' },
        { value: 'DC', label: 'District Of Columbia' },
        { value: 'FL', label: 'Florida' },
        { value: 'GA', label: 'Georgia' },
        { value: 'HI', label: 'Hawaii' },
        { value: 'ID', label: 'Idaho' },
        { value: 'IL', label: 'Illinois' },
        { value: 'IN', label: 'Indiana' },
        { value: 'IA', label: 'Iowa' },
        { value: 'KS', label: 'Kansas' },
        { value: 'KY', label: 'Kentucky' },
        { value: 'LA', label: 'Louisiana' },
        { value: 'ME', label: 'Maine' },
        { value: 'MD', label: 'Maryland' },
        { value: 'MA', label: 'Massachusetts' },
        { value: 'MI', label: 'Michigan' },
        { value: 'MN', label: 'Minnesota' },
        { value: 'MS', label: 'Mississippi' },
        { value: 'MO', label: 'Missouri' },
        { value: 'MT', label: 'Montana' },
        { value: 'NE', label: 'Nebraska' },
        { value: 'NV', label: 'Nevada' },
        { value: 'NH', label: 'New Hampshire' },
        { value: 'NJ', label: 'New Jersey' },
        { value: 'NM', label: 'New Mexico' },
        { value: 'NY', label: 'New York' },
        { value: 'NC', label: 'North Carolina' },
        { value: 'ND', label: 'North Dakota' },
        { value: 'OH', label: 'Ohio' },
        { value: 'OK', label: 'Oklahoma' },
        { value: 'OR', label: 'Oregon' },
        { value: 'PA', label: 'Pennsylvania' },
        { value: 'RI', label: 'Rhode Island' },
        { value: 'SC', label: 'South Carolina' },
        { value: 'SD', label: 'South Dakota' },
        { value: 'TN', label: 'Tennessee' },
        { value: 'TX', label: 'Texas' },
        { value: 'UT', label: 'Utah' },
        { value: 'VT', label: 'Vermont' },
        { value: 'VA', label: 'Virginia' },
        { value: 'WA', label: 'Washington' },
        { value: 'WV', label: 'West Virginia' },
        { value: 'WI', label: 'Wisconsin' },
        { value: 'WY', label: 'Wyoming' },
    ],
};

export const companyTypes = [
    { value: "Bakery" },
    { value: "Bar or Night Club" },
    { value: "Butcher Shop" },
    { value: "Cafe" },
    { value: "Caterer" },
    { value: "Cheese Shop" },
    { value: "Chocolate Shop" },
    { value: "Cocktail & Kitchen Supplies Store" },
    { value: "Distributor" },
    { value: "Gourmet Grocery Store" },
    { value: "Grill Store" },
    { value: "Health Food Store" },
    { value: "Hotel" },
    { value: "Ice Cream Shop" },
    { value: "Liquor Store" },
    { value: "Manufacturer" },
    { value: "Pastry Shop" },
    { value: "Resort" },
    { value: "Restaurant" },
    { value: "Seafood Market" },
    { value: "Spice Store" },
    { value: "Other" },

];

export const cuisineTypes = [
    { value: 'Asian Cuisine' },
    { value: 'Breakfast Restaurant' },
    { value: 'British Foods, Pub' },
    { value: 'French Cuisine' },
    { value: 'Gourmet Burger Restaurant' },
    { value: 'Italian Cuisine' },
    { value: 'Local Ingredients Focused' },
    { value: 'Mexican or Taco' },
    { value: 'Modern or Fusion Style' },
    { value: 'Pizzeria' },
    { value: 'Spanish Cuisine' },
    { value: 'Steakhouse' },
    { value: 'Vegan Food' },
    { value: 'Vegetarian Food' },
    { value: 'Other' },
];

export const employees = [
    {value: "10", label: "10 or Less"},
    {value: "50", label: "11 to 50"},
    {value: "100", label: "51 to 100"},
    {value: "200", label: "101 to 200"},
    {value: "500", label: "201 to 500"},
    {value: "500+", label: "Over 500"},
];

export const spendAmounts = [
    {value: "10000", label: "$10,000 or Less"},
    {value: "50000", label: "$10,001 to $50,000"},
    {value: "100000", label: "$50,001 to $100,000"},
    {value: "150000", label: "$100,001 to $150,000"},
    {value: "200000", label: "$150,001 to $200,000"},
    {value: "200000+", label: "Over $200,000"},
];
